language: python
cache: pip
matrix:
  fast_finish: true
  include:
    - { python: "3.7", env: DJANGO=2.2 }
    - { python: "3.7", env: DJANGO=3.2 }
  allow_failures:
    - env: DJANGO=main
install:
  - pip install tox tox-travis
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls
